config/routes.rb
Rails.application.routes.draw do

  namespace :madmin do
    resources :users
    root to: "dashboard#show"
  end
  mount StripeEvent::Engine, at: '/stripe/webhook' # provide a custom path

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: "registrations" }
  root to: 'pages#index'

  resource :subscription
  resource :card

  get 'about' => 'pages#about'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:facebook, :twitter]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

  def subscribed?
    stripe_subscription_id?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end
  helper_method :current_user_subscribed?

  def after_sign_up_path_for(resource)
    if params[:plan] == "free" or ""
      root_path # as defined in config/routes.rb
    elsif params[:plan] == "monthly"
      new_subscription_path
    end
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :authenticate_user!

	def update
	    customer = Stripe::Customer.retrieve(current_user.stripe_id)
	    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
	    subscription.source = params[:stripeToken]
	    subscription.save

	    current_user.update(
	      card_last4: params[:card_last4],
	      card_exp_month: params[:card_exp_month],
	      card_exp_year: params[:card_exp_year],
	      card_type: params[:card_brand]
	    )

	    redirect_to edit_user_registration_path, notice: "Successfully updated your card"
	end
end

app/controllers/madmin/application_controller.rb
module Madmin
  class ApplicationController < Madmin::BaseController
    before_action :authenticate_admin_user

    def authenticate_admin_user
      # TODO: Add your authentication logic here

      # For example, we could redirect if the user isn't an admin
      # redirect_to "/", alert: "Not authorized." unless user_signed_in? && current_user.admin?
    end

    # Authenticate with Clearance
    # include Clearance::Controller
    # before_action :require_login

    # Authenticate with Devise
    # before_action :authenticate_user!

    # Authenticate with Basic Auth
    # http_basic_authenticate_with(name: Rails.application.credentials.admin_username, password: Rails.application.credentials.admin_password)
  end
end

app/controllers/madmin/users_controller.rb
module Madmin
  class UsersController < Madmin::ResourceController
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:planid, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:planid, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :redirect_to_signup, only: [:new]

  def show
  end

  def new
  end

  def create
    customer = if current_user.stripe_id?
                 Stripe::Customer.retrieve(current_user.stripe_id)
               else
                 Stripe::Customer.create(email: current_user.email)
               end

    subscription = customer.subscriptions.create(
      source: params[:stripeToken],
      plan: current_user.planid
    )

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
    }

    # Only update the card on file if we're adding a new one
    options.merge!(
      card_last4: params[:card_last4],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year],
      card_type: params[:card_brand]
    ) if params[:card_last4]

    current_user.update(options)

    redirect_to root_path
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)

    redirect_to root_path, notice: "Your subscription has been canceled."
  end

  def plans
    @stripe_list = Stripe::Plan.all
    @plans = @stripe_list[:data]
  end

  private

    def redirect_to_signup
      if !user_signed_in?
        session["user_return_to"] = new_subscription_path
        redirect_to new_user_registration_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_fields_class
    "hidden" if current_user.card_last4?
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'shared/head' %>
</head>
<body>

<%= render 'shared/navbar' %>
<%= render 'shared/notices' %>

<div class="container mx-auto">
  <%= yield %>
</div>

<%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/madmin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="ROBOTS" content="NOODP">
    <meta name="viewport" content="initial-scale=1">
    <title>
      Madmin: <%= Rails.application.class %>
    </title>
    <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@tailwindcss/forms/dist/forms.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@tailwindcss/typography/dist/typography.min.css" rel="stylesheet" />
    <%= csrf_meta_tags %>

    <%= render "javascript" %>
  </head>
  <body class="prose" style="max-width:none">
    <div class="flex w-full p-4">
      <div id="sidebar" class="w-64 flex-shrink-0">
        <%= render "navigation" -%>
      </div>
      <main class="w-full" role="main">
        <%#= render "flashes" -%>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/madmin/application/_form.html.erb
<%= form_with model: [:madmin, record], url: (record.persisted? ? resource.show_path(record) : resource.index_path), local: true do |form| %>
  <% if form.object.errors.any? %>
    <div class="mb-4 rounded-md text-sm text-red-700 bg-red-100 p-4">
      <div class="mb-2 font-medium leading-5 text-red-800">There was <%= pluralize form.object.errors.full_messages.count, "error" %> with your submission</div>

      <% form.object.errors.full_messages.each do |message| %>
        <div class="ml-4"><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <% resource.attributes.each do |attribute| %>
    <% next if attribute[:field].nil? %>
    <% next unless attribute[:field].visible?(action_name) %>
    <% next unless attribute[:field].visible?(:form) %>

    <% field = attribute[:field] %>

    <div class="mb-4 flex">
      <%= render partial: field.to_partial_path("form"), locals: { field: field, record: record, form: form, resource: resource } %>
    </div>
  <% end %>

  <%= form.submit class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
<% end %>

app/views/madmin/application/_javascript.html.erb
<%= stylesheet_link_tag "https://unpkg.com/flatpickr/dist/flatpickr.min.css", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "https://unpkg.com/trix/dist/trix.css", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "https://unpkg.com/slim-select@1.27.0/dist/slimselect.min.css", "data-turbo-track": "reload" %>

<script type="module">
  import { Application, Controller } from 'https://cdn.skypack.dev/stimulus'
  const application = Application.start()

  import stimulusFlatpickr from 'https://cdn.skypack.dev/stimulus-flatpickr'
  application.register("flatpickr", stimulusFlatpickr)

  import stimulusSlimselect from 'https://cdn.skypack.dev/stimulus-slimselect'
  application.register("slimselect", stimulusSlimselect)

  import Rails from 'https://cdn.skypack.dev/@rails/ujs@<%= npm_rails_version %>'
  import * as ActiveStorage from 'https://cdn.skypack.dev/@rails/activestorage@<%= npm_rails_version %>'
  import 'https://cdn.skypack.dev/trix'
  import 'https://cdn.skypack.dev/@rails/actiontext@<%= npm_rails_version %>'

  if (!window._rails_loaded) { Rails.start() }
  ActiveStorage.start()

  import * as Turbo from "https://cdn.skypack.dev/@hotwired/turbo"

  (() => {
    application.register('nested-form', class extends Controller {
      static get targets() {
        return [ "links", "template" ]
      }

      connect() {
        this.wrapperClass = this.data.get("wrapperClass") || "nested-fields"
      }

      add_association(event) {
        event.preventDefault()

        var content = this.templateTarget.innerHTML.replace(/NEW_RECORD/g, new Date().getTime())
        this.linksTarget.insertAdjacentHTML('beforebegin', content)
      }

      remove_association(event) {
        event.preventDefault()

        let wrapper = event.target.closest("." + this.wrapperClass)

        // New records are simply removed from the page
        if (wrapper.dataset.newRecord == "true") {
          wrapper.remove()

        // Existing records are hidden and flagged for deletion
        } else {
          wrapper.querySelector("input[name*='_destroy']").value = 1
          wrapper.style.display = 'none'
        }
      }
    })
  })()
</script>

app/views/madmin/application/_navigation.html.erb
<div class="text-sm">
  <%= link_to "← Back to App", main_app.root_url, class: "block p-1", data: { turbo: false } if main_app.respond_to?(:root_url) %>
  <% Madmin.resources.each do |resource| %>
    <%= link_to resource.friendly_name.pluralize, resource.index_path, class: "block p-1" %>
  <% end %>
</div>

app/views/madmin/application/edit.html.erb
<h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / Edit <%= resource.friendly_name %> #<%= @record.id %></h1>

<%= render partial: "form", locals: { record: @record, resource: resource } %>

app/views/madmin/application/index.html.erb
<div class="flex justify-between">
  <h1><%= resource.friendly_name.pluralize %></h1>
  <%= link_to "New #{resource.friendly_name}", resource.new_path %>
</div>

<div>
  <% if resource.scopes.any? %>
    <%= link_to "All", resource.index_path %>
  <% end %>

  <% resource.scopes.each do |scope| %>
    <%= link_to scope.to_s.humanize, resource.index_path(scope: scope) %>
  <% end %>
</div>

<table class="table-auto">
  <thead>
    <tr>
      <% resource.attributes.each do |attribute| %>
        <% next if attribute[:field].nil? %>
        <% next unless attribute[:field].visible?(action_name) %>

        <th><%= sortable attribute[:name], attribute[:name].to_s.titleize %></th>
      <% end %>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <% resource.attributes.each do |attribute| %>
          <% next if attribute[:field].nil? %>
          <% next unless attribute[:field].visible?(action_name) %>

          <% field = attribute[:field] %>

          <td><%= render partial: field.to_partial_path("index"), locals: { field: field, record: record } %></td>
        <% end %>

        <td><%= link_to "View", resource.show_path(record) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/madmin/application/new.html.erb
<h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / New <%= resource.friendly_name %></h1>

<%= render partial: "form", locals: { record: @record, resource: resource } %>

app/views/madmin/application/show.html.erb
<div class="flex justify-between">
  <h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / <%= resource.model.name.singularize %> #<%= @record.id %></h1>

  <div class="flex px-4">
    <%= link_to "Edit", resource.edit_path(@record), class: "mr-2" %>
    <%= button_to "Delete", resource.show_path(@record), method: :delete, data: { confirm: "Are you sure?" }, class: "inline-block" %>
  </div>
</div>

<% resource.attributes.each do |attribute| %>
  <% next if attribute[:field].nil? %>
  <% next unless attribute[:field].visible?(action_name) %>
  <% field = attribute[:field] %>

  <div class="flex py-2">
    <div class="w-32 flex-shrink-0 text-gray-700 uppercase tracking-wide text-sm">
      <%= field.attribute_name.to_s.titleize %>
    </div>

    <div>
      <%= render partial: field.to_partial_path("show"), locals: { field: field, record: @record } %>
    </div>
  </div>
<% end %>

app/views/pages/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron mt-5 mb-5">
        <h1>SaaS Rocket!</h1>
        <p>This is a quick starter Rails application to help get a SaaS application started. When it is finished it should include handling everything from OmniAuth user authentication to subscribing and charging via plans in Stripe.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Devise and OmniAuth</h2>
          <p>Start by setting up your facebook and twitter API keys so that users can choose to login via email, facebook, or twitter. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Subscriptions with Stripe</h2>
          <p>Assign a plan to a user and start charging them for access to content and other software/services. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Design with Bootstrap</h2>
          <p>Use bootstrap to design a responsive and attractice layout for your users to enjoy.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

app/views/pages/pricing.html.erb
<%= form_tag subscription_path(1), :method => :put do %>
<% @plans.each do |plan| %>
  <div class=”plan”>
  <h1><%= plan[:name] %></h1>
  <p>£<%= plan[:amount]/100 %></p>

  </div>
<% end %>
<% end %>

app/views/shared/_footer.html.erb
 <footer class="text-center text-white mt-4" style="background-color: darkslateblue">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register on SaaS Rocket for free</span>
           <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-outline-light btn-rounded" %>
         
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://xhostcom.com/">SaaS Rocket</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/shared/_head.html.erb
<title><%= content_for?(:title) ? yield(:title) : "Rails SaaS Rocket" %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= tag :meta, name: "stripe-key", content: Rails.application.secrets.stripe_publishable_key %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container mx-auto">
    <%= link_to image_tag "Logo.png", width: '150', class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>
      <ul class="navbar-nav">
        <%= form_tag(root_path, :method => "get",
                     class: 'navbar-form navbar-left') do %>
          <div class="input-group">
            <%= text_field_tag :title, params[:title], placeholder: "Search By Title", class: "form-control" %>
          </div>
        <% end %>
        <li class="nav-item"><%= link_to "Users", root_path, class: "btn btn-link nav-link mx-2" %></li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link mx-2" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag root_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item"><%= link_to "Add New Course", new_course_path, class: "btn btn-info nav-link mx-2" %></li>


        <% else %>
          <li class="nav-item mx-1"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info nav-link mx-2" %></li>
          <li class="nav-item mx-1"><%= link_to "Login", new_user_session_path, class: "btn btn-warning nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


 

app/views/shared/_notices.html.erb
<div class="container mx-auto">
  <% flash.each do |msg_type, message| %>
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/subscriptions/new.html.erb
<div class="container">
  <h1>Sign Up Today!</h1>

  <%= form_tag subscription_path, id: "payment-form" do %>
    <% if current_user.card_last4? %>
      <div class="card-on-file">
        <p>Your current card on file is:</p>
        <div><%= current_user.card_type %> **** **** **** <%= current_user.card_last4 %></div>
        <div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>

        <p><%= link_to "Use a different card", "#", class: "use-different-card" %></p>
      </div>
    <% end %>

    <div class="card-fields <%= card_fields_class %>">
      <span class="payment-errors"></span>

      <div class="form-row">
        <label>
          <span>Card Number</span>
          <input value="4242 4242 4242 4242" type="text" size="20" data-stripe="number"/>
        </label>
      </div>

      <div class="form-row">
        <label>
          <span>CVC</span>
          <input value="123" type="text" size="4" data-stripe="cvc"/>
        </label>
      </div>

      <div class="form-row">
        <label>
          <span>Expiration (MM/YYYY)</span>
          <input value="12" type="text" size="2" data-stripe="exp-month"/>
        </label>
        <span> / </span>
        <input value="2020" type="text" size="4" data-stripe="exp-year"/>
      </div>
    </div>

    <button type="submit">Submit Payment</button>
  <% end %>
</div>